<?php

namespace App\Http\Controllers;

use App\Models\Wallet;
use App\Models\LedgerEntry;
use Illuminate\Http\Request;

class LedgerController extends Controller
{
    public function index(Request $request, string $wallet_id): \Illuminate\Http\JsonResponse
    {
        $wallet = Wallet::findOrFail($wallet_id);

        /** @var \App\Models\User $user */
        $user = $request->user();

        // Security check: Only the wallet owner can view their ledger
        if ($wallet->user_id !== $user->id) {
            return response()->json(['message' => 'Unauthorized access to wallet.'], 403);
        }

        // Use a SQL subquery to fetch the complete double-entry pair across all wallets
        // Then use MySQL's native JSON_ARRAYAGG to perform the grouping at the database level
        //this helps me to avoid using php loops to roup ledger entries
        $entries = LedgerEntry::select(
            'transaction_reference',
            \Illuminate\Support\Facades\DB::raw('JSON_ARRAYAGG(JSON_OBJECT(
                    "id", id,
                    "transaction_reference", transaction_reference,
                    "wallet_id", wallet_id,
                    "type", type,
                    "amount", amount,
                    "description", description,
                    "created_at", created_at,
                    "updated_at", updated_at
                )) as entries')
        )
            ->whereIn('transaction_reference', function ($query) use ($wallet) {
                // Subquery: Find all transaction references that involved THIS wallet
                $query->select('transaction_reference')
                    ->from('ledger_entries')
                    ->where('wallet_id', $wallet->id);
            })
            ->groupBy('transaction_reference')
            ->orderByRaw('MAX(created_at) DESC')
            ->paginate(20);

        // Decode the JSON strings generated by MySQL back into PHP arrays for the final JSON response
        $mapped = $entries->getCollection()->map(function (\App\Models\LedgerEntry $item) {
            return [
                'transaction_reference' => $item->transaction_reference,
                'entries' => json_decode((string) $item->getAttribute('entries'), true)
            ];
        });
        
        $entries->setCollection($mapped);

        return response()->json([
            'wallet_balance_kobo_or_fen' => $wallet->balance,
            'currency' => $wallet->currency,
            'ledger' => $entries
        ]);
    }
}
